w4d3/NinetyNineCats/config/routes.rb
NinetyNineCats::Application.routes.draw do
  root to: 'cats#index'
  resources :cats
  resources :cat_rental_requests

end

w4d3/NinetyNineCats/app/models/cat.rb
class Cat < ActiveRecord::Base
  COLORS = ["blue", "black", "brown", "white"]

  validates :age, :numericality =>  {:only_integer => true}
  validates :color, inclusion: {in: COLORS, message: "Invalid Color"}
  validates :sex, inclusion: {in: ["M", "F"], message: "Invalid Sex"}
  validates :age, :birth_date, :color, :name, :sex, :presence => true

  has_many :cat_rental_requests, dependent: :destroy


end

w4d3/NinetyNineCats/app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  STATUSES = ["PENDING", "APPROVED", "DENIED"]

  before_validation(on: :create) do
    self.status ||= "PENDING"
  end

  validates :cat_id, :start_date, :end_date, :status, :presence => true
  validates :status, inclusion: {in: STATUSES, message: "Invalid Status"}
  validate  :overlapping_approved_requests

  belongs_to :cat


  def overlapping_requests
    overlaps = self.cat.cat_rental_requests
           .where("cat_id = ? AND ((start_date BETWEEN ? AND ?)
                   OR  (end_date BETWEEN ? AND ?))", self.cat_id, self.start_date,
                   self.end_date, self.start_date, self.end_date)
  end

  def overlapping_approved_requests
    if !overlapping_requests.where("status = ?", "APPROVED").empty?
      errors.add(:request, "date not available")
    end
  end

  def approve!
    ActiveRecord::Base.transaction do
      self.status = "APPROVED" unless overlapping_approved_requests
      self.save!
    end
  end

  def deny!
    ActiveRecord::Base.transaction do
      self.status = "DENIED"
      self.save!
    end
  end

end

w4d3/NinetyNineCats/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session


end

w4d3/NinetyNineCats/app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController


  def index
    @requests = CatRentalRequest.all
    render :index
  end

  before_action :find_request, only: [:show, :edit, :update, :destroy]


  def show
    render :show
  end

  def new
    @request = CatRentalRequest.new
    render :new
  end

  def edit

    render :edit
  end

  def update
    if @request.update_attributes(request_all_params)
      redirect_to cat_rental_request_url(@request)
    else
      render :edit
    end
  end

  def approve
    @request.approve!
  end

  def deny
    @request.deny!
    # CatRentalRequest.delete(@request)
  end


  # def update # @post = Post.find(params[:id]) # if @post.update_attributes(post_params) # redirect_to post_url(@post) # else # flash.now[:errors] = @post.errors.full_messages # render :edit # end # end def create @cat = Cat.new(cat_all_params)

  def create
    @request = CatRentalRequest.new(request_all_params)

    if @request.save
      redirect_to cat_rental_requests_url
    else
      # flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  private
  def find_request
    @request = CatRentalRequest.find(params[:id])
  end

  def request_all_params
    # {request: {cat_id: 4, start_date: '12013', ...}}
    params.require(:request).permit(:cat_id, :start_date, :end_date, :status)
  end

end

#
# cat_rental_requests GET    /cat_rental_requests(.:format)          cat_rental_requests#index
#                         POST   /cat_rental_requests(.:format)          cat_rental_requests#create
#  new_cat_rental_request GET    /cat_rental_requests/new(.:format)      cat_rental_requests#new
# edit_cat_rental_request GET    /cat_rental_requests/:id/edit(.:format) cat_rental_requests#edit
#      cat_rental_request GET    /cat_rental_requests/:id(.:format)      cat_rental_requests#show
#                         PATCH  /cat_rental_requests/:id(.:format)      cat_rental_requests#update
#                         PUT    /cat_rental_requests/:id(.:format)      cat_rental_requests#update
#                         DELETE /cat_rental_requests/:id(.:format)      cat_rental_requests#destroy

w4d3/NinetyNineCats/app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :find_cat, only: [:show, :edit, :update, :destroy]

  def index
    @cats = Cat.all
    render :index
  end

  def show
    render :show
  end

  def new
    @cat = Cat.new
    render :new
  end

  def edit
    render :edit
  end

  def update
    if @cat.update_attributes(cat_all_params)
      redirect_to cat_url(@cat)
    else
      render :edit
    end
  end


  # def update
#     @post = Post.find(params[:id])
#     if @post.update_attributes(post_params)
#       redirect_to post_url(@post)
#     else
#       flash.now[:errors] = @post.errors.full_messages
#       render :edit
#     end
#   end
  def create
    @cat = Cat.new(cat_all_params)

    if @cat.save
      redirect_to cats_url
    else
      # flash.now[:errors] = @cat.errors.full_messages
      render :new
    end
  end

  private
  def find_cat
    @cat = Cat.find(params[:id])
  end

  def cat_all_params
    params.require(:cat).permit(:age, :birth_date, :color, :name, :sex)
  end
end


#   Prefix Verb   URI Pattern              Controller#Action
#     cats GET    /cats(.:format)          cats#index
#          POST   /cats(.:format)          cats#create
#  new_cat GET    /cats/new(.:format)      cats#new
# edit_cat GET    /cats/:id/edit(.:format) cats#edit
#      cat GET    /cats/:id(.:format)      cats#show
#          PATCH  /cats/:id(.:format)      cats#update
#          PUT    /cats/:id(.:format)      cats#update
#          DELETE /cats/:id(.:format)      cats#destroy

w4d3/NinetyNineCats/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d3/NinetyNineCats/app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

w4d3/NinetyNineCats/app/helpers/cats_helper.rb
module CatsHelper
end

w4d3/NinetyNineCats/app/views/cat_rental_requests/edit.html.erb
<h2>Edit Request!</h2>

<%= @request.errors.full_messages.each {|error| error unless error.empty? } unless @request.errors.empty? %>

<%= render :partial => "layouts/request_form" %>

w4d3/NinetyNineCats/app/views/cat_rental_requests/index.html.erb
<h1>All your cats</h1>
<ul>
  <% @requests.each do |request| %>
  <li><%= request.inspect %> <%= link_to "request", cat_rental_request_url(request) %> </li>
  <% end %>
</ul>

<%= link_to "Create new cat rental request!!", new_cat_rental_request_url %>

w4d3/NinetyNineCats/app/views/cat_rental_requests/new.html.erb
<h2>New Request!!</h2>



<%= @request.errors.full_messages.each {|error| error unless error.empty? } unless @request.errors.empty? %>

<%= render :partial => "layouts/request_form" %>

w4d3/NinetyNineCats/app/views/cat_rental_requests/show.html.erb
<h1><%= "Request##{@request.id}"%> </h1>
<ul>
  <table cellpadding="10", cellspacing= "10", frame="border", rules="all">


    <tr>
       <th> Cat Name </th>
      <%  @request.attributes.keys.each do |key| %>
      <th><%= key %></th>
      <% end %>
    </tr>

    <tr>
      <td> <%= Cat.find(@request.cat_id).name %> </td>
      <%  @request.attributes.values.each do |val| %>
      <td><%= val %></td>
      <% end %>

    </tr>



  </table>
</ul>

<%= link_to "GET A CAT!", new_cat_rental_request_url %>
<br>
<%= link_to "Edit your REQUEST", edit_cat_rental_request_url(@request)%>

w4d3/NinetyNineCats/app/views/cats/edit.html.erb
<h2>Cat Edit form!</h2>

<%= @cat.errors.full_messages.each {|error| error unless error.empty? } unless @cat.errors.empty? %>

<%= render :partial => "layouts/form" %>

w4d3/NinetyNineCats/app/views/cats/index.html.erb
<h1>All your cats</h1>
<ul>
  <% @cats.each do |cat| %>
  <li><%= cat.inspect %> <%= link_to "Go to Cat", cat_url(cat) %> </li>
  <% end %>
</ul>

<%= link_to "Create new cat!", new_cat_url %>

w4d3/NinetyNineCats/app/views/cats/new.html.erb
<h2>Cat form!</h2>



<%= @cat.errors.full_messages.each {|error| error unless error.empty? } unless @cat.errors.empty? %>

<%= render :partial => "layouts/form" %>

w4d3/NinetyNineCats/app/views/cats/show.html.erb
<h1><%= "Cat ##{@cat.id}"%> </h1>
<ul>
  <table cellpadding="10", cellspacing= "10", frame="border", rules="all">
    <tr>
      <%  @cat.attributes.keys.each do |key| %>
      <th><%= key %></th>
      <% end %>
    </tr>

    <tr>
      <%  @cat.attributes.values.each do |val| %>
      <td><%= val %></td>
      <% end %>

    </tr>

  </table>
</ul>

<%= link_to "Create new cat!", new_cat_url %>
<br>
<%= link_to "Edit cat", edit_cat_url(@cat)%>

w4d3/NinetyNineCats/app/views/layouts/_form.html.erb
<form action="<%= @cat.persisted? ? cat_url(@cat) : cats_url %>" method="post">

  <% if @cat.persisted? %>
  <input type = "hidden" name="_method" value ="patch">
  <% end %>

  <label for="cat_age">Age</label>
  <input name="cat[age]" id="cat_age" type="number" value=<%= @cat.age %>>
  <br>


  <label for="cat_birth_date">Birth date</label>
  <!-- click on the date will launch a date picker -->
  <input name="cat[birth_date]" id="cat_birth_date" type="date"
  value=<%= @cat.birth_date %>></input>

  <br>

  <label for="cat_color">Cat color</label>
  <!-- dropdown -->
  <select name="cat[color]">
    <!-- `brown` is the value that will be submitted to the server; user is
         displayed "Brown" as the choice -->

      <% ([""] + Cat::COLORS).each do |color| %>

      <% if @cat.color == color%>
          <option value = <%= color %> selected = "selected"> <%= color%> </option>
      <% else %>
          <option value = <%= color %>> <%= color %> </option>
        <% end %>
      <% end %>

      <!--% if @cat.nil? %-->
        <!--option selected="selected" value="%<= @cat.color %>"> <%= @cat.color %> </option-->
      <!--% end%-->



  </select>
  <br>

 <label for="cat_name"> Name</label>

  <input name="cat[name]" id="cat_name" type="text" value=<%= @cat.name %> >
  <br>

  <label>Sex</label>
  <div>
    <!-- note that both radio buttons have the name `cat[sex]`; that's how
         they are related -->


      <% ["M", "F"].each do |sex| %>
      <% if @cat.sex == sex%>
      <input name="cat[sex]" id="cat_sex_<%= sex %>"
            type="radio" value= <%= sex %>   checked>
      <label for="cat_sex_<%=sex%>"><%= sex %></label>
      <% else %>
      <input name="cat[sex]" id="cat_sex_<%= sex %>"
             type="radio" value= <%= sex %>>
      <label for="cat_sex_<%=sex%>"><%= sex %></label>
        <% end %>
      <% end %>

  </div>
  <br>


   <input type="submit" value="Build my cat!">

 </form>

w4d3/NinetyNineCats/app/views/layouts/_request_form.html.erb
<form action="<%= @request.persisted? ? cat_rental_request_url(@request) : cat_rental_requests_url %>" method="post">

  <% if @request.persisted? %>
  <input type = "hidden" name="_method" value ="patch">
  <% end %>


  <label for="request_cat_name">Requested Cat Name</label>
  <!-- dropdown -->
  <select name="request[cat_id]" id ="request_cat_name">
    <!-- `brown` is the value that will be submitted to the server; user is
         displayed "Brown" as the choice -->
      <% Cat.all.each do |cat| %>
      <option value = "<%= cat.id %>"><%= cat.name %> </option>
      <% end %>

  </select>
  <br>




  <label for="request_start_date">Start Date</label>
  <!-- click on the date will launch a date picker -->
  <input name="request[start_date]" id="request_start_date" type="date"
  value=<%= @request.start_date %>></input>

  <label for="request_end_date">End Date</label>
  <!-- click on the date will launch a date picker -->
  <input name="request[end_date]" id="request_end_date" type="date"
  value=<%= @request.start_date %>></input>
  <hr>
   <input type="submit" value="I can has cat??!">
</form>

w4d3/NinetyNineCats/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>NinetyNineCats</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>