w4d3/PostsDemo/config/routes.rb
PostsDemo::Application.routes.draw do
  root to: "posts#index"
  resources :posts do
    resources :comments, :only => [:index, :new, :create]
  end
  resources :comments, :except => [:index, :new, :create]
end

w4d3/PostsDemo/app/models/comment.rb
# == Schema Information
#
# Table name: comments
#
#  id         :integer          not null, primary key
#  post_id    :integer
#  content    :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Comment < ActiveRecord::Base
  belongs_to :post
end

w4d3/PostsDemo/app/models/post.rb
# == Schema Information
#
# Table name: posts
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  body       :string(255)
#  created_at :datetime
#  updated_at :datetime
#

class Post < ActiveRecord::Base
  validates :title, :presence => true
  has_many :comments
end

w4d3/PostsDemo/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  # protect_from_forgery with: :exception
end

w4d3/PostsDemo/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = Post.all

    render :index
  end

  def new
    @post = Post.new
    render :new
  end

  def create
    @post = Post.new(post_params)
    if @post.save
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :new, :status => 422
    end
  end

  def edit
    @post = Post.find(params[:id])
    render :edit
  end

  def update
    @post = Post.find(params[:id])
    if @post.update_attributes(post_params)
      redirect_to post_url(@post)
    else
      flash.now[:errors] = @post.errors.full_messages
      render :edit
    end
  end

  def show
    @post = Post.find(params[:id])

    render :show
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy if @post
    redirect_to posts_url
  end

  private
  # def set_post
  #   @post = Post.find(params[:id])
  # end

  def post_params
    params.require(:post).permit(:title, :body)
  end
end

w4d3/PostsDemo/app/helpers/application_helper.rb
module ApplicationHelper
end

w4d3/PostsDemo/app/helpers/posts_helper.rb
module PostsHelper
end

w4d3/PostsDemo/app/views/layouts/_errors.html.erb
<% if flash[:errors] %>
  <%= flash[:errors] %>
<% end %>

w4d3/PostsDemo/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PostsDemo</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

w4d3/PostsDemo/app/views/posts/edit.html.erb
<%= render :partial => "layouts/errors" %>

<form action="<%= post_url(@post) %>" method="post" accept-charset="utf-8">
  <input type="hidden" name="_method" value="PATCH" />
  <label for="title">Title</label>
  <input type="text" name="post[title]" id="title" 
         value="<%= @post.title %>" />

  <label for="body">Body</label>
  <input type="text" name="post[body]" id="body" 
         value="<%= @post.body %>" />

  <input type="hidden" name="post[categories][]" />
  <label for="1">category 1</label>
  <input type="checkbox" name="post[categories][]" value="1" id="1" />
  <label for="2">category 2</label>
  <input type="checkbox" name="post[categories][]" value="2" id="2" />

  <input type="submit" />
</form>

w4d3/PostsDemo/app/views/posts/index.html.erb
<ul>
  <% @posts.each do |post| %>
  <li>
  <%= link_to(post.title, post_url(post)) %>

  <%= button_to("Delete", post_url(post), :method => :delete) %>
  </li>
  <% end %>
</ul>


<%= link_to "Add Post", new_post_url %>

w4d3/PostsDemo/app/views/posts/new.html.erb
<%= render :partial => "layouts/errors" %>

<form action="<%= posts_url %>" method="post">
  <label for="title">Title</label>
  <input type="text" name="post[title]" id="title" 
         value="<%= @post.title %>" />

  <label for="body">Body</label>
  <input type="text" name="post[body]" id="body" 
         value="<%= @post.body %>" />

  <input type="submit" />
</form>

w4d3/PostsDemo/app/views/posts/show.html.erb
<h1>
  <%= @post.title %>
</h1>

<p>
  <%= @post.body %>
</p>

<%= link_to "Back to Posts", posts_url %>
<%= link_to "Edit Post", edit_post_url(@post) %>